---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    - homebrew/dupes
    brew_packages:
    - git
    - zsh
    - vim
    - the_silver_searcher
    - ctags
    - reattach-to-user-namespace
    - tmux
    - mysql
    - ansible
    - mosh
    - watch
    - libxslt
    - libxml2
    - libiconv
    cask_packages:
    - font-inconsolata-for-powerline
    - iterm2
    - macvim
    - firefox
    - google-chrome
    - dropbox
    - spectacle
    - caffeine
    - mailbox
    - clipmenu
